
### File Integrity Monitoring
```xml
<syscheck>
  <disabled>no</disabled>
  <scan_on_start>yes</scan_on_start>
  <alert_new_files>yes</alert_new_files>

  <directories check_all="yes" realtime="yes" report_changes="yes">C:\Users\*\Downloads </directories>
</syscheck>
